# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [2]:
np.empty(10)

array([-2.31584178e+077, -2.31584178e+077,  2.47032823e-323,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
       -2.31584178e+077,  1.73060109e-077,  9.88131292e-324,
        6.95335581e-309])

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
a = np.empty(10)
a[4] = 1
a

array([-2.31584178e+077,  2.68678950e+154,  2.47032823e-323,
        0.00000000e+000,  1.00000000e+000,  0.00000000e+000,
       -2.68678950e+154,  1.49457627e-154,  9.17549210e-072,
        6.95336403e-309])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [54]:
b = np.random.randint(10, 50, size = (10))
print(b)

[41 39 14 31 48 37 15 42 15 30]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [56]:
b[::-1]

<class 'numpy.ndarray'>


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [43]:
np.random.randint(0,9, size = (3,3))

array([[8, 6, 5],
       [5, 5, 3],
       [1, 4, 1]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [66]:
c = np.array([1,2,0,0,4,0])
indices = np.where(c > 0)
print(indices)

(array([0, 1, 4]),)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [69]:
np.random.rand(3,3,3)

array([[[0.56477509, 0.25858762, 0.63042832],
        [0.57861184, 0.64759318, 0.50598817],
        [0.02839441, 0.60677887, 0.9774587 ]],

       [[0.31637697, 0.24150976, 0.94245558],
        [0.98203807, 0.88373548, 0.96363377],
        [0.28425692, 0.75023614, 0.3782337 ]],

       [[0.26787074, 0.95681775, 0.2036917 ],
        [0.54683024, 0.82080038, 0.91634564],
        [0.92445468, 0.10796565, 0.37913436]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [80]:
d = np.random.rand(10,10)
#print(d)
minValue = np.min(d)
maxValue = np.max(d)
print(minValue)
print(maxValue)

0.007893936931753442
0.9923588503573368


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [82]:
e = np.random.rand(30)
np.mean(e)

0.4280529924490581

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [92]:
f = np.ones((6,6), dtype = 'int32')
g = np.zeros((4,4), dtype = 'int32')
f[1:5,1:5] = g
f

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [95]:
#Use numpy.pad to add a border
h = np.full((3,3), 2)
np.pad(h, 1)

array([[0, 0, 0, 0, 0],
       [0, 2, 2, 2, 0],
       [0, 2, 2, 2, 0],
       [0, 2, 2, 2, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
False
False
nan
True
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [101]:
i = np.zeros((5,5))
i[[1,2,3,4],[0,1,2,3]] = [1,2,3,4]
i

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [111]:
# We know the size of the array is 6 * 7 * 8 = 336
# so we can initialize an array of this size with
# ascending values and use np.where to pull the correct
# indices. This is probably more complicated than necessary

j = np.arange(336).reshape((6,7,8))
np.where(j==99)

#(1,5,3)

(array([1]), array([5]), array([3]))

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [117]:
k = np.random.rand(5,5)
norm = np.linalg.norm(k)
normalizedArray = k/norm
normalizedArray

array([[0.04041349, 0.15515814, 0.20645782, 0.01918346, 0.19199781],
       [0.23361849, 0.33127813, 0.26719664, 0.01239188, 0.22259352],
       [0.03953787, 0.05325846, 0.28777224, 0.22684694, 0.09960846],
       [0.14424358, 0.2342458 , 0.23201616, 0.298569  , 0.27088449],
       [0.04748063, 0.18448343, 0.13242046, 0.33798193, 0.01839343]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [125]:
l = np.array([1,2,3,4,5,6,7,8,9])
#l = np.where((3 < l < 8), -l, l)
mask = (l > 3) & (l < 8)
l[mask] *= -1
l

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 29. How to round away from zero a float array ? (★☆☆)

In [128]:
#By using np.ceil
m = np.array([2.1, 4.6, 8.1])
np.ceil(m)

array([3., 5., 9.])

#### 30. How to find common values between two arrays? (★☆☆)

In [133]:
n = np.array([2, 5, 7, 9])
o = np.array([1, 5, 7, 11])
n[n == o]

array([5, 7])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
#No, it's False

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [151]:
from random import randrange
def number_generator():
    values = []
    for i in range(10):
        values.append(randrange(100))
    return values

p = np.asarray(number_generator())
print(p)

[80 19 56 86 72 66  6 11 17 79]


10

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [156]:
q = np.linspace(0,1,12)[1:-1]
q

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [158]:
r = np.random.rand(10)
np.sort(r)

array([0.3176791 , 0.34121628, 0.38576741, 0.48440175, 0.50313276,
       0.57138332, 0.59530732, 0.60860926, 0.75018016, 0.86834395])

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [162]:
A = np.array([1,2,3])
B = np.array([1,2,3])
np.all(A == B)

True

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [171]:
s = np.random.rand(10)
#print(s)
max_index = np.where(s == np.amax(s))
s[max_index] = 0
#print(s)

[0.46289511 0.89033845 0.26499323 0.8467406  0.39829908 0.55508956
 0.00882938 0.35011011 0.27521611 0.47818489]
[0.46289511 0.         0.26499323 0.8467406  0.39829908 0.55508956
 0.00882938 0.35011011 0.27521611 0.47818489]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [179]:
#subtract scalar from elements in array
#take absolute value
#min of array is correct value
def closestValue(scalar, vector):
    values = np.abs(vector - scalar)
    print(values)
    return vector[np.where(values == np.amin(values))]

scalar_num = 10
t = np.array([1, 5, 7, 9, 12, 15])
result = closestValue(scalar_num, t)
print(result)

[9 5 3 1 2 5]
[9]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [189]:
u = np.array([5.1, 7.5])
print(u.dtype)
u = u.astype(int)
print(v.dtype)

float64
int64


#### 59. How to sort an array by the nth column? (★★☆)

In [193]:
#someArray[someArray[:,n].argsort()]
#where n is the column you wish to sort by

#This example sorts by the 3rd column
v = np.array([[7,8,9],[4,5,6],[1,3,17]])
print(v)
v[v[:,2].argsort()]

[[ 7  8  9]
 [ 4  5  6]
 [ 1  3 17]]


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  3, 17]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [211]:
v = np.array([[1,5],[9,8]])
print((~v.any(axis=0).any()))

False


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [219]:
x = np.array([1, 2, 3, 4, 5])
y = np.zeros(len(x) + (len(x)-1) * 3)
y[::4] = x
print(y.astype(int))

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 72. How to swap two rows of an array? (★★★)

In [228]:
A = np.array([[3,5],[4,2],[8,9]])
print(A)
A[[0,2]] = A[[2,0]]
print(A)

[[3 5]
 [4 2]
 [8 9]]
[[8 9]
 [4 2]
 [3 5]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [240]:
#Use '~' to negate a boolean
#Multiply float by -1

B = np.array([[3,5],[-4,2],[8,9]])
print(B)
print((B > 4))
print((~(B > 4)))

B[1,0] = B[1,0] * -1
print(B)

[[ 3  5]
 [-4  2]
 [ 8  9]]
[[False  True]
 [False False]
 [ True  True]]
[[ True False]
 [ True  True]
 [False False]]
[[3 5]
 [4 2]
 [8 9]]


#### 83. How to find the most frequent value in an array?

In [244]:
from collections import Counter
D = np.array([5,6,6,6,3,4,9,0,6])
E = Counter(D)
print(E.most_common(1))

[(6, 4)]


#### 89. How to get the n largest values of an array (★★★)

In [260]:
#perform a sort on the array
#then specifiy with a slice
#how many values you want

F = np.random.randint(1,10, size=10)
G = np.sort(F)

# in this case I want 3 values

G[-3:]

array([6, 7, 8])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [264]:
A = np.array([[3,5],[4,2],[3,5],[4,2],[8,9]])
A
print(np.unique(A, axis=0))

[[3 5]
 [4 2]
 [8 9]]
